version: '3.7'
services:
  spring-app-blue:
    image: spring-example:latest
    container_name: spring-app-blue
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: amigoscode
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

  spring-app-green:
    image: spring-example:latest
    container_name: spring-app-green
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: amigoscode
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
