version: '3'
services:
  app-blue:
    image: faycalraghibi/ci-cd-deployment-pipeline:latest
    container_name: app-blue
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8081"  #  Map Tomcat's port 8081 to host port 8081
    networks:
      - app-network

  app-green:
    image: faycalraghibi/ci-cd-deployment-pipeline:latest
    container_name: app-green
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8082:8081"  #  Map Tomcat's port 8081 to host port 8082
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge




